### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by luerhard** [AntonHardock/wptab#2]
Ich schreibe jetzt mal auf deutsch, lest ja doch niemand im Internet :)

Das Testfile ist ein bisschen albern - denn es tut exakt nix, dass man sehen kann :) (Ich nehme an, du hast den Code aus einem Notebook rauskopiert, aber als .py file ergibt das so keinen Output.

Grundsätzlich kann ich Dir testing schwer ans Herz legen und empfehlen - Dazu vielleicht mal in die Dokumentation von [pytest](https://docs.pytest.org/en/latest/) reinschauen. Super cool, super mächtig (etwas einschüchternd zu Beginn, evtl)

[Hier](https://realpython.com/python-testing/) ist sonst mal ein Einführungstutorial dazu.

**Comment by AntonHardock** [comment]
Danke für das Feedback. Das Testfile sollte gar nicht sichtbar sein, 
hab es wohl aus Versehen zum Repo hinzugefügt, bevor ich es auf .gitignore sezte.

Und danke für den Tipp zu pytest, das schaue ich mir beim nächsten Projekt mal genauer an.
